# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roland', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Publication',
        ),
    ]
