# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roland', '0002_auto_20170415_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
