MODEL_PUBLICATION_TITLE_LENGTH = 200
MODEL_PUBLICATION_CONTENT_LENGTH = 2000

MODEL_MANUAL_TITLE_LENGTH = 200
MODEL_MANUAL_DESCRIPTION_LENGTH = 2000

MODEL_CATEGORY_NAME_LENGTH = 200
MODEL_CATEGORY_CONTENT_LENGTH = 16000

INDEX_PUB_PER_PAGES = 5

TIME_NOW = lambda:datetime.now()

LOGIN_URL = '/roland/login/'