MODEL_GROUP_NAME = 150
MODEL_ARENA_NAME = 150
MODEL_CITY_NAME = 150
MODEL_STATS_MAX_LENGTH = 10
MODEL_USER_AVATAR = 'profile_picture'
MODEL_USER_FIRST_NAME = 30
MODEL_USER_LAST_NAME = 30
MODEL_USER_KNOWN_AS = 150
MODEL_USER_IMAGE_SIZE = (128, 128)
MODEL_USER_COUNTRIES = (
	('ND', 'Not defined'),
	('AL','Albania'),
	('AR','Argentina'),
	('AU','Australia'),
	('AT','Austria'),
	('AZ','Azerbaijan'),
	('BD','Bangladesh'),
	('BY','Belarus'),
	('BE','Belgium'),
	('BA','Bosnia And Herzegovina'),
	('BR','Brazil'),
	('IO','British Indian Ocean Territory'),
	('BG','Bulgaria'),
	('CA','Canada'),
	('CL','Chile'),
	('CN','China'),
	('CO','Colombia'),
	('CR','Costa Rica'),
	('HR','Croatia'),
	('CU','Cuba'),
	('CY','Cyprus'),
	('CZ','Czech Republic'),
	('DK','Denmark'),
	('DO','Dominican Republic'),
	('EC','Ecuador'),
	('EG','Egypt'),
	('SV','El Salvador'),
	('GQ','Equatorial Guinea'),
	('EE','Estonia'),
	('FI','Finland'),
	('FR','France'),
	('DE','Germany'),
	('GR','Greece'),
	('GL','Greenland'),
	('HK','Hong Kong'),
	('HU','Hungary'),
	('IS','Iceland'),
	('IN','India'),
	('ID','Indonesia'),
	('IE','Ireland'),
	('IL','Israel'),
	('IT','Italy'),
	('JM','Jamaica'),
	('JP','Japan'),
	('KZ','Kazakhstan'),
	('KP','Korea,Democratic Peoples Republic Of'),
	('KR','Korea,Republic Of'),
	('KW','Kuwait'),
	('LV','Latvia'),
	('LB','Lebanon'),
	('LT','Lithuania'),
	('LU','Luxembourg'),
	('MK','Macedonia,The Former Yugoslav Republic Of'),
	('MT','Malta'),
	('MX','Mexico'),
	('MD','Moldova,Republic Of'),
	('MC','Monaco'),
	('ME','Montenegro'),
	('MA','Morocco'),
	('NL','Netherlands'),
	('AN','Netherlands Antilles'),
	('NZ','New Zealand'),
	('NI','Nicaragua'),
	('NO','Norway'),
	('PY','Paraguay'),
	('PE','Peru'),
	('PL','Poland'),
	('PT','Portugal'),
	('PR','Puerto Rico'),
	('RO','Romania'),
	('RU','Russian Federation'),
	('RS','Serbia'),
	('SK','Slovakia'),
	('SI','Slovenia'),
	('ES','Spain'),
	('LK','Sri Lanka'),
	('SE','Sweden'),
	('CH','Switzerland'),
	('TW','Taiwan'),
	('TH','Thailand'),
	('TR','Turkey'),
	('UA','Ukraine'),
	('GB','United Kingdom'),
	('US','United States')
)

LOGIN_URL ='/pachangapp/login/'