MODEL_GROUP_NAME = 150
MODEL_ARENA_NAME = 150
MODEL_CITY_NAME = 150
MODEL_STATS_MAX_LENGTH = 10
MODEL_USER_FIRST_NAME = 30
MODEL_USER_LAST_NAME = 30
MODEL_USER_KNOWN_AS = 150


LOGIN_URL = '/pachangapp/login/'